<a href="https://colab.research.google.com/github/jaggusuperhit/Machine-learning/blob/main/day16.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import pandas as pd

# Woking with JSON

In [20]:
pd.read_json('train.json')

ValueError: Unmatched ''"' when when decoding 'string'

In [21]:
pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2024-03-28,1711584001,0.0440
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2024-03-28,1711584001,0.8570
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2024-03-28,1711584001,1.1500
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2024-03-28,1711584001,4.7500
ANG,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2024-03-28,1711584001,0.0215
...,...,...,...,...,...,...,...
XPF,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2024-03-28,1711584001,1.3200
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2024-03-28,1711584001,3.0100
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2024-03-28,1711584001,0.2270
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2024-03-28,1711584001,0.3030
ZWL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2024-03-28,1711584001,246.5300

# Working with SQL

In [18]:
!pip install mysql.connector

Requirement already satisfied: mysql.connector in /usr/local/lib/python3.10/dist-packages (2.2.9)

In [ ]:
import mysql.connector

In [23]:
conn = mysql.connector.connect(host='localhost',user='root',password='',database='world')

InterfaceError: 2003: Can't connect to MySQL server on 'localhost:3306' (111 Connection refused)

In [ ]:
df = pd.read_sql_query("SELECT * FROM countrylanguage",conn)

In [ ]:
df

    CountryCode    Language IsOfficial  Percentage
0           ABW       Dutch          T         5.3
1           ABW     English          F         9.5
2           ABW  Papiamento          F        76.7
3           ABW     Spanish          F         7.4
4           AFG     Balochi          F         0.9
..          ...         ...        ...         ...
979         ZMB      Tongan          F        11.0
980         ZWE     English          T         2.2
981         ZWE     Ndebele          F        16.2
982         ZWE      Nyanja          F         2.2
983         ZWE       Shona          F        72.1

[984 rows x 4 columns]